# Generated by Django 5.0.7 on 2024-08-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField()),
                ('ativo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinteId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Pedido Realizado'), ('2', 'Pedido em Preparo'), ('3', 'Pedido Pronto'), ('4', 'Pedido Entregue')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedidoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pedido')),
                ('produtoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.produto')),
            ],
        ),
    ]
