# Generated by Django 5.0.7 on 2024-08-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='clinteId',
            new_name='clienteId',
        ),
    ]
